<div class='about'>
    <div class='about__header'>
    <div>
        <div class='column-header'>
        <h2>ABOUT</h2>
        <h3>关于极客沙龙</h3>
        </div>
        <div class='about__desc column-container'>极客沙龙是由京东凹凸实验室主办的技术主题沙龙，每个季度举办。我们会邀请行业内的优秀团队与我们一起分享技术经验，畅谈工作心得。欢迎您的参与！</div>
    </div>
    <div class='about__img'><img src='//img10.360buyimg.com/ling/jfs/t1/103459/24/18467/8527/5e935af8E291edcc9/7e5d3507fc833d9a.jpg'></img></div>
    </div>
</div>