<header class="head head-index">
    <div class="container">
        <a class="logo" href="{{url_for('/')}}"><span class="logo-pic"></span></a>
        <div class="head-links">
            <a  href="#topic">大咖开讲</a>
            <a  href="#round-table">圆桌讨论</a>
            <a  href="#address">会议地址</a>
            <a  href="#review">往期回顾</a>
            <a  href="https://l.jd.com/student/project/project.du?project_id=88665377
">立即报名</a>
        </div>
    </div>
</header>

